language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install: make install
script: make test
addons:
  sauce_connect: true
env:
  global:
  - secure: JZ5unPxbhiASVL2A4yL7+gUce0paPFBeicAambO7FT7MeAO61XRwI2vEOzRpllwIsxIEUGZ9LpishZJGkzTWMQ8F4T1VaxHXjA2N+6bCiNnz/DMXoMwUHcgoqSlZ6gzMeS4m3T4d8w5PV/TedXLyf3moWCM5ecqqJwY2851QCPc=
  - secure: Lv2dKAq9XuIJ5zXThcHaTOtfFnfThxAqgR1v3RT/PjYj+VKxnnXFjIkYrqcuZbGl43t2WmKpPecMDaXSQTNaxUiCBTemLhKSdI2GwH66P8wKJBl6E93F2M2ozJu29xrqUDyJKXNRWLV5zzw4QfpkSym7TalTsL/XHcAku5qei6Y=
  - secure: boKckXJwvvVjJ39VE7Fruceb0+H7k6O9Yebr7IEZK8ix20e8xgQIbpW5BFNDvbO8GEHiv+bGLJVOwMWR2sKSSrEsu4IGlM3DseSfNLzRVECQBKPa48aG5trqDAuToR39cAqmJkI+wEZ2D2fBP6Tbd0g/1lp/yADkRFfhtO3Z1RA=
