language: ruby
rvm:
- 2.0.0
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install --quiet -g bower gulp karma protractor
- npm install --quiet
- bower install --quiet
script: npm test
env:
  global:
    secure: YgYFUynbXzplBm8wPX6kUvza/xPPj8MXtzYCWMugrN1qjbIBTZfMzwdCmhIybBITbDMXO76XztzXYk2QU2LdZVzqrcceIRCGBf8CJGzohg74Ce3KUSk+XrH3H3UdGmNKq/2HBe4eDOzVMBgm2QTKHe6hdl7rTARkq3FZ/r5SKOI=
